using CentralChat.Application;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace CentralChat.Infrastructure;

/// <summary>
/// Stores media on the host filesystem, backed by a Docker volume. Deliberately behind
/// <see cref="IMediaStore"/>: moving to S3-compatible object storage later replaces this one class
/// and nothing else, because callers only ever see an opaque storage key.
/// </summary>
public sealed class FileSystemMediaStore(IOptions<MediaOptions> options, ILogger<FileSystemMediaStore> logger) : IMediaStore
{
    private readonly MediaOptions _options = options.Value;

    public async Task<string> SaveAsync(Stream content, string extension, CancellationToken ct)
    {
        // Sharded by month so no single directory accumulates every file the workspace has ever received.
        var now = DateTimeOffset.UtcNow;
        var folder = Path.Combine(now.ToString("yyyy"), now.ToString("MM"));
        var name = $"{Guid.NewGuid():N}{Normalise(extension)}";
        var key = $"{folder.Replace(Path.DirectorySeparatorChar, '/')}/{name}";

        var absolute = ResolveOrThrow(key);
        Directory.CreateDirectory(Path.GetDirectoryName(absolute)!);

        await using (var file = File.Create(absolute))
        {
            await content.CopyToAsync(file, ct);
        }

        logger.LogInformation("Stored media {Key} ({Bytes} bytes)", key, new FileInfo(absolute).Length);
        return key;
    }

    public Task<Stream?> OpenAsync(string key, CancellationToken ct)
    {
        var absolute = ResolveOrThrow(key);
        if (!File.Exists(absolute)) return Task.FromResult<Stream?>(null);
        return Task.FromResult<Stream?>(File.OpenRead(absolute));
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var absolute = ResolveOrThrow(key);
        if (File.Exists(absolute)) File.Delete(absolute);
        return Task.CompletedTask;
    }

    /// <summary>
    /// Keys are generated by this class, never supplied by a caller — but they travel through the
    /// database and an HTTP route, so resolving one that escapes the media root is treated as an attack
    /// rather than trusted.
    /// </summary>
    private string ResolveOrThrow(string key)
    {
        var root = Path.GetFullPath(_options.Root);
        var absolute = Path.GetFullPath(Path.Combine(root, key));
        if (!absolute.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal) && absolute != root)
            throw new ForbiddenException("Media key resolved outside the media root.");
        return absolute;
    }

    private static string Normalise(string extension)
    {
        if (string.IsNullOrWhiteSpace(extension)) return string.Empty;
        var trimmed = extension.Trim().TrimStart('.');
        // Only ever a short alphanumeric suffix; anything else is dropped rather than written to disk.
        return trimmed.Length is > 0 and <= 8 && trimmed.All(char.IsLetterOrDigit) ? "." + trimmed.ToLowerInvariant() : string.Empty;
    }
}
